# Generated by Django 3.2.23 on 2024-03-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='picture',
            field=models.ImageField(upload_to='img/shop/', verbose_name='图片'),
        ),
    ]
