# Generated by Django 3.2.23 on 2024-03-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shopinfo_picture'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shopinfo',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='num',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
    ]
