# Generated by Django 3.2.23 on 2024-03-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20240315_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='title',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
    ]
