# Generated by Django 3.2.23 on 2024-03-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shopinfo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopinfo',
            name='isDelete',
        ),
    ]
