"""
Django settings for 二手市场 project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import time
from alipay import AliPay
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h2nf&leh9_2d+#t$!)%hja4a140-+(qvjxh!y+@cy7_v&gwwqi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'shop',
    'order',
    'captcha'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '二手市场.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '二手市场.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'shop',
        'USER': 'root',
        'PASSWORD': 'ypjhwcf',
        'HOST': 'localhost',
        'POST': '3306',
    }
}

CAPTCHA_FONT_SIZE = 24  # 字体的像素大小，默认为22
CAPTCHA_IMAGE_SIZE = (100, 25)  # 以生成的验证码像素为单位的图像大小，指定为元组(宽度，高度)。默认为None
CAPTCHA_LITTER_ROTATION = (-15, 15)  # 在此区间内的随机旋转文本中的字符。默认为(-35, 35)
CAPTCHA_BACKGROUND_COLOR = 'red'  # 验证码背景颜色，可以表示为html风格的#rrggbb, rgb(red，green，blue)，又或者常见的html名字，例如red。默认为#ffffff
CAPTCHA_FOREGROUND_COLOR = '#ffffff'  # 验证码前景色，默认为#001100
CAPTCHA_MATH_CHALLENGE_OPERATOR = 'x'  # 在使用math_challenge时，允许您选择乘法运算符。例如采用"x"代替。默认为*
CAPTCHA_WORDS_DICTIONARY = None  # 包含单词列表的文件目录。只有当CAPTCHA_CHALLENGE_FUNCT设置为captcha.helpers.word_challenge
# 或captcha.helpers.huge_words_and_punctuation_challenge时需要。默认为/usr/share/dict/words
CAPTCHA_FLITE_PATH = None  # 音频读取器所在目录。定义时，将自动读取验证码。默认为None
CAPTCHA_TIMEOUT = 1  # 验证码的有效期，单位为分钟。默认为5
CAPTCHA_LENGTH = 4  # 用于设置生成的验证码的长度，只有当CAPTCHA_CHALLENGE_FUNCT设置为captcha.helpers.random_char_challenge时需要。默认为4
CAPTCHA_DICTIONARY_MIN_LENGTH = 0  # 控制从CAPTCHA_WORDS_DICTIONARY目录中随机抽取的单词的最小长度，只有当设置为
# captcha.helpers.word_challenge或captcha.helpers.huge_words_and_punctuation_challenge时需要。默认为0
CAPTCHA_DICTIONARY_MAX_LENGTH = 99  # 控制从CAPTCHA_WORDS_DICTIONARY目录中随机抽取的单词的最大长度，只有当设置为
# captcha.helpers.word_challenge或captcha.helpers.huge_words_and_punctuation_challenge时需要。默认为99
CAPTCHA_TEST_MODE = False  # 当设置为True时，字符串PASSED在任何情况下将被接受为对任何验证码的有效响应。用于测试目的。默认为False
# 设置输出的格式，该插件自动在模板中生成3个元素：一个验证码图片，一个验证码输入框、一个用于存放秘钥的隐藏输入框。可以在此根据需要调整其在模板中生成的先后顺序
CAPTCHA_OUTPUT_FORMAT = '%(text_field)s %(image)s %(hidden_field)s '
# 图像过滤器。可调用对象的字符串列表，以PIL Image对象作为参数输入，修改并返回它。
CAPTCHA_NOISE_FUNCTIONS = (
    # 'captcha.helpers.noise_null',  # 没有样式
    # 'captcha.helpers.noise_arcs',  # 线
    'captcha.helpers.noise_dots',  # 点
)
# 图片中的文字为随机英文字母，如 mdsh 用于显示验证码内容与结果的可调用对象。如 2 + 2 =  'captcha.helpers.math_challenge'
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'
# 验证码输入框指定 TEMPLATE, 表单使用 CaptchaField 字段生效
# CAPTCHA_TEXT_FIELD_TEMPLATE = "captcha_text_field.html"

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_CACHE_ALIAS = "session"


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
MEDIA_ROOT = os.path.join(BASE_DIR, "static/")
MEDIA_URL = '/img/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

alipay_public_key_string = '''-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgXegJNG4ost+f9o28cRzzfSJKg8Ce/ICdhOxH962acaPKUJjCo35o2whnVGjGqvTbUAKZDYFC5vod+PHZqS3CBy0TwMXPOLlZKVQ+/806inFrnqorZeLAICZO4E2UbMM8o0hLkchy8gXP6ep4WjbsPP9wCxsQTRLTJlHClmXrp84bYbC8LhVM/BgQuh2/3KM5w/r8G3mCqEyFZI8W3TzIxAi+E1RU9z3tOKc4ChLOhv6Y4ECa3dkDV80o/S+ddCyARKnmWrgYF8c3Q1g0SQ4BAwCjMVEi7lnyTD2LY69R3NkE9IV6Kii6TLk3p8cMycajNU2ohbck146tgWgCiPWnQIDAQAB
-----END PUBLIC KEY-----'''
app_private_key_string = '''-----BEGIN PRIVATE KEY-----
MIIEpQIBAAKCAQEAt0CqxQ5s6kq5UnDuToGnZ0OEhf/zkBUYwixfF2+Jicvw5M+vT+Bpg5h4kqUoCqtlGYK8rZkHhJRY+9B0+3FdfofCQOocosBwbqrpSvhfH+tGaIT6M4F7oxWhWjmj2zHy4yj2lSqqoLM0ZOcIs3sTcMAKpgsdWo0tGLiQ0tXswT8FQloMptUjbi10LXTfRIVegZUYB0BObBL+vfzIhVDhPklsqgS3BJ5NM4XjW8PUw0x6oSywOj9g0F40a06FxrXK/GdvdOy9EQokSwCwVMUVxBmUvxeULtK619cI6AUU/F213Ws1nt32UphjHykx6jwLvgerwXeUn62ATpMLFpNhqwIDAQABAoIBAQCq7gzb5gq9t5mJRoFihRlq/tV8UDQV7ze61ryUFZvLBonaQ8aY0RBaiTvePWNOIHUbCJGJs7YJen5N1DFp4GJ/BY6yEi1HugyljZIyNd403bY9A9yFcn+qrSBmEmG+saaHMMxgcv3ZC48Rl1bMYz7M6rSEENX+grTP3EhqANTnopVwZk9ZDjh6r/Sx5Rbpoje2vsLZr7kXPDL8lvNol0xMNK5wObenDdDFLtu3Tay+KiJquI3ovGLcwX2rC+eo58WG6AkmQj+rTTSwFV1FtgSG6ZjUNlG2nOkzfPJ+Y6ODHIZb+tIv6BZ28t0vUFRdKh99QhzBrCuGyh4lhS7EgdxhAoGBAOvvUk6MEpyEeiaawi10nZEoMuOvdQy/FMnXA9n/BtEXTT9MYAOuuruGvLGsUiaruM9uVuynafJBB/rgU9lsdfCW74/2+s5fyucrXYhPMD4r4no91A8Pzcc+7um4GxktusKTWGphU3jARktn74f2j5S6AnOJGfUWa0PEduRdwgoDAoGBAMbWXnTHZBo+gF+l8ArbwJCyjFXcNa6UXyldoTKJSw5ahjzfo+nqf9Mo1p/w4pdaYHup20ObGWSjb8943VShrcoRyh8Au4ISOW883AvKoxAb9FWamn4SydIVukHU1lW7lxwGr9PDgedrAAUHbpUMacRvFDHyoGwBaHm7q9EMnw05AoGBAIkeJW+Q6KAePf+BoahZRdm+yxSYPCaURrinRY3EMWoDaNmIwaRiQBQMUk3QIE5pLpcfQVV4VpJ8SO78wL5z0ndowQGiQFEASyPeiBVYMGlxh8YTeNLoFGffo2ohnV4cvZWnnJL2zVQ4KqJYXVVfbkK5eAM9guB1jxFrdM1zz/mRAoGAa6wwECrdMT0BRUpVd3vShki5p9EMnNIpyfuyy+v+4fHxWUt9trDOsWke+BN4kJ9XOgAcBTsbAB1k8cOwjyDSPGdvvWQnJeN6iJs7SYNc099fa2/CE11XPtWXPAjmXByuUnXohtMLKGcP5qlEn5/OMpo4JGgPqQ0GJ02SWCzugDkCgYEA0nhYdYnNu9XdXIcSqN+jqA3RXuQPBgwhiLL1R/zYrFXvNOljhOUNnBwB8E1QnQYcwXbXdecxxPC/ipsRST32S02Jrqh3/+PYy+z7geD2OVqBaNi9g8R4bJB41wE+X+7N+YY8gr4B1P/BtUuAzzI5RhjxBaDuBI0+K19E6h/qOnM=
-----END PRIVATE KEY-----'''
