# Generated by Django 3.2.23 on 2024-03-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, verbose_name='用户姓名')),
                ('password', models.CharField(max_length=20, verbose_name='用户密码')),
                ('picture', models.ImageField(upload_to='user/', verbose_name='头像')),
                ('sex', models.CharField(max_length=10, verbose_name='性别')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号码')),
                ('address', models.CharField(max_length=20, verbose_name='地址')),
            ],
        ),
    ]
