# Generated by Django 3.2.23 on 2024-03-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240314_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='picture',
            field=models.ImageField(upload_to='static/img/head_img', verbose_name='头像'),
        ),
    ]
