# Generated by Django 3.2.23 on 2024-03-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32, unique=True, verbose_name='订单编号')),
                ('order_date', models.DateField(auto_now=True, verbose_name='订单日期')),
                ('order_status', models.IntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '待发货'), (3, '待收货'), (4, '完成'), (5, '拒收')], verbose_name='订单状态')),
                ('order_total', models.FloatField(verbose_name='订单总价')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo', verbose_name='订单用户')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_count', models.IntegerField(verbose_name='商品数量')),
                ('goods_total_price', models.FloatField(verbose_name='商品小计')),
                ('goods_price', models.FloatField(verbose_name='商品单价')),
                ('status', models.IntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '已发货'), (3, '已完成'), (4, '拒绝发货')], default=0, verbose_name='订单状态')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='user.userinfo', verbose_name='买家')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shopinfo', verbose_name='商品表')),
                ('order_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.payorder', verbose_name='订单表外键')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_id', to='user.userinfo', verbose_name='卖家id')),
            ],
        ),
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo', verbose_name='买家')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shopinfo', verbose_name='商品')),
            ],
        ),
    ]
