# Generated by Django 3.2.23 on 2024-03-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
