# Generated by Django 3.2.23 on 2024-03-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_payorder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartinfo',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='goods_count',
            field=models.IntegerField(default=1, verbose_name='商品数量'),
        ),
    ]
