# Generated by Django 3.2.23 on 2024-03-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20240315_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartinfo',
            name='number',
            field=models.IntegerField(default=1, verbose_name='商品数量'),
        ),
    ]
